# -*- mode:toml; -*-
[module.userspace-application-group]
    initappfiles = [ "app/init.cc", "app/ThreadManager.cc", "app/Thread.cc", "app/SignalGroup.cc" ]
	incfiles = [ 	"app/Thread.hh",
					"app/Mutex.hh",
					"app/SignalGroup.hh",
					"app/ISignalable.hh",
					"app/ThreadManager.hh",
					"app/conf.hh",
					"app/HelperThreadBenchmark.hh",
					"app/TreeMulticastBenchmark.hh",
          "app/SequentialMulticastBenchmark.hh",
					"app/Task.hh",
					"app/IntrusiveList.hh" ,
				]
    provides = [ "app/init.elf" ]
    requires = [ "crtbegin" ]
    makefile_head = '''
TARGETS += app/init.elf

INITAPP_CXX = $(APP_CXX)
INITAPP_AS = $(APP_AS)
INITAPP_CXXFLAGS = $(APP_CXXFLAGS)
INITAPP_CPPFLAGS = $(APP_CPPFLAGS)
'''
    makefile_body = '''
app/init.elf: $(INITAPPFILES_OBJ) $(APPFILES_OBJ) $(CRTFILES_OBJ)
	$(APP_CXX) $(APP_LDFLAGS) $(APP_CXXFLAGS) -nostdlib -o $@ app/start.o app/crtbegin.o -lgcc $(INITAPPFILES_OBJ) $(APPFILES_OBJ) app/crtend.o
	$(NM)  $@ | cut -d " " -f 1,3 | c++filt -t > init.sym
	$(OBJDUMP) -dS $@ | c++filt > init.disasm
	$(STRIP) $@
'''
